defaults:
  - override hydra/launcher: submitit_chunked_slurm

hydra:
  launcher:
    max_experiments_per_job: 2
    joblib:
      n_jobs: -1 # all available cpu's per job for running multiple experiments


task: ???